# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Contour
                                 A QGIS plugin
 This plugin creates a line feature class of contours from a raster surface
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-12-30
        copyright            : (C) 2019 by Rajat Shakya
        email                : rajat.181cv232@nitk.edu.in
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Contour class from file Contour.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .contour import Contour
    return Contour(iface)
